### PR TITLE
print get_cursor() function with mouse.move text.

### PR DESCRIPTION
**Pull request by mrchypark**

### CODE REVIEW

**Comment by jeffkeller87** [comment]
The purpose of `get_cursor` is to return a vector that can be used by other functions. Turning this into a printing function would diminish its value.

**Comment by mrchypark** [comment]
oh, it maybe print option is better.

**Comment by mrchypark** [comment]
this pr dead?

**Comment by jeffkeller87** [comment]
This seems like unnecessary complexity. Why wouldn't a user just do something like this:

```
print(mouse.get_cursor())
```

**Comment by mrchypark** [comment]
I think print option is to record. 

maybe support to record mouse and keyboard event and build script function, It's usefull.

**Pull request closed without merging**
